### ISSUE TITLE
Feature Request: Compass Vibration on Facing North

### ISSUE THREAD

**Issue by rob0tster** [mtrewartha/positional#27]
Hi there! I'm a big fan of your app and had a feature request that I think would be a great addition:

I'd love to have a mode in the background that vibrates whenever the phone turns north to help instill a passive sense of where north is.

I totally understand if this is outside of your intended scope, but anyways there's my idea.

Thanks!

**Comment by mtrewartha** [comment]
Sorry, I somehow missed this until now!

I think the vibration on north is a great idea. I've been thinking for some time now that it could be fun to inject a little personality into the app with some more sound, animation, or vibration. This seems like a tasteful, subtle, and useful thing to do. It could be made optional so folks could disable it, too.

When you say "mode in the background" do you mean you'd like to be able to leave/background the app (or lock your phone) but still have the app vibrate when you turn north?

**Comment by rob0tster** [comment]
Hey no problem at all. I'm thrilled that you like the idea! 

Yeah that's exactly what I was thinking with the background part. My thought is if you feel a light buzz in your pocket while walking around, your brain will passively build up a sense of where north is and help build up directional sense while not grabbing too much attention.

**Comment by mtrewartha** [comment]
It sounds like there are actually two smaller requests here then:

1. Do these vibrations when the app is in the foreground.
2. Do these vibrations when the app is in the background.

It's important to me to split out the background part because I would guess most people don't want the app to keep the compass or location going in the background when they leave the app. When someone _does_ want that behavior, they'd need an easy way of basically telling the app "Keep running when I lock my phone or leave the app". They would also need some way to turn that off, obviously. It sounds very similar to the existing screen lock on/off functionality.

I'm totally happy to do the foreground vibrations, so I'll plan to knock that out when I get a chance. I'll have to sleep on the background ones, but I'd imagine they could be built in a way that maintained the simplicity and minimalism I value in this app. An extra icon button on the Compass screen and a system notification for a [foreground service](https://developer.android.com/guide/components/foreground-services) would likely be all that's required.

**Comment by mtrewartha** [comment]
@rob0tster Configurable foreground vibration will be rolling out via the Play Store once Google approves. I'm rolling out to 10% of users to start, so you might not get the update right away, but I'll quickly ramp up once I see stability in the build. I'd love to hear any feedback you might have once you get it!

**Comment by rob0tster** [comment]
The update looks great! I love the configurable length of vibration and I think it meets the 'noticeable' but 'not too much' margins really well

Some thoughts I had were:
1. Would a configurable vibration range be possible?
 - for example crossing between -15 degrees and +15 degrees of north could be a vibration instead of just 0
 - that might be helpful for if a person isn't as concerned with 'exact' north vs. just in the general direction

2. Is vibration intensity a configurable option? 
- I'm not familiar with anything android dev, but when wearing something tougher like jeans the vibration is harder to notice, so maybe a harder vibration option would help

Thanks!

**Comment by Hellboy00000** [comment]
This keep wasting battery life when the app is closed or killed? Because in another compass app i read this:

Privacy Policy - FOREGROUND_SERVICE - Allows the app to continuously receive GPS, magnetometer, and gyroscope readings,
even if the UI is killed by Android) https://www.ericbt.com/ebt_compass/privacypolicy

Thanks.

**Comment by mtrewartha** [comment]
@Hellboy00000 No, Positional doesn't use the `FOREGROUND_SERVICE` permission and shouldn't run at all in the background.
